//
// Created by bill on 2025 12 05.
//

#ifndef RS_MOTOR_ROS2_ROBSTRIDEMOTORRECEIVER_H
#define RS_MOTOR_ROS2_ROBSTRIDEMOTORRECEIVER_H

class RobStrideMotorReceiver
{

};


#endif //RS_MOTOR_ROS2_ROBSTRIDEMOTORRECEIVER_H